// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavoritesIconController from "./favorites_icon_controller"
application.register("favorites-icon", FavoritesIconController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StripeController from "./stripe_controller"
application.register("stripe", StripeController)
