meta_product_name: "WaxWorks"
meta_title: "WaxWorks - Where vinyl collections come alive"
meta_description: "Discover and buy vinyl records"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@waxworks_vinyl"   # required for Twitter Cards
